### ISSUE TITLE
Request.download_small_db  -- multiprocessing -- freeze_support -- runtime error

### ISSUE THREAD

**Issue by lsawade** [PyGLImER/PyGLImER#103]
I included as many helpers in the issue as possible. At the moment, request.download_small_db has to be inside a 

```python
if '__main__' == __name__:

    request.download_small_db(...)

    request.preprocess(...)
```

statement. This is due a backend issue with multiprocessing. See [Issue #101](https://github.com/PyGLImER/PyGLImER/issues/101#issue-1204902059)

This makes a universal example hard to show

**Comment by PeterMakus** [comment]
Is this solved now? I have no way of testing things on MACOS

**Comment by lsawade** [comment]
It is not really solved. It works in the creation of the docs now without issue. This will error on a mac if not wrapped in the if __name...

Will change the example to tell people about it. Otherwise, this can be left.
